// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/0-s0g0/TEKUTEKU/server/db"
	"github.com/0-s0g0/TEKUTEKU/server/internal/app/handler"
	"github.com/0-s0g0/TEKUTEKU/server/internal/app/repository"
	"github.com/0-s0g0/TEKUTEKU/server/internal/app/service"
)

// Injectors from wire.go:

func InitHandler() *handler.Root {
	queries := db.New()
	iUserRepository := repository.NewUserRepository(queries)
	iStorageRepository := repository.NewStorageRepository()
	iUserService := service.NewUserService(iUserRepository, iStorageRepository)
	iUserHandler := handler.NewUserHandler(iUserService)
	iMessageRepository := repository.NewMessageRepository(queries)
	iMessageService := service.NewMessageService(iMessageRepository)
	iMessageHandler := handler.NewMessageHandler(iMessageService)
	root := handler.New(iUserHandler, iMessageHandler)
	return root
}
